apiVersion: v1
kind: Service
metadata:
  name: endpoint-root-svc
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: endpoint-root

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-blue-svc
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: endpoint-blue

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-green-svc
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: endpoint-green

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-vip-svc
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: endpoint-vip
